version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nestjs

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    links:
      - postgres:postgres

  postgres:
    image: postgres:15-alpine
    restart: always

    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
