name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/dev-wiki && git pull origin main && echo "DB_HOST=${{ secrets.DB_HOST }}" \
            "DB_NAME=${{ secrets.DB_NAME }}" \
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            "DB_PORT=${{ secrets.DB_PORT }}" \
            "DB_SYNCHRONIZE=${{ secrets.DB_SYNCHRONIZE }}" \
            "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" \
            "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
            "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" \
            >> .env.production && echo "DB_HOST=${{ secrets.DB_HOST }}" \
            "DB_NAME=${{ secrets.DB_NAME }}" \
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            "DB_PORT=${{ secrets.DB_PORT }}" \
            "DB_SYNCHRONIZE=${{ secrets.DB_SYNCHRONIZE }}" \
            "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" \
            "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
            "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" \
            >> .env.development && docker-compose down && docker-compose up -d
